name: Docker Image CI
on:
  push:
    branches: ["main"]

jobs:
  build-penguincs-login:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/ermilburn02/penguincs-login
          tags: |
            type=ref,event=branch
            type=sha
          labels: |
            org.opencontainers.image.source=https://github.com/ERmilburn02/PenguinCS-V2
            org.opencontainers.image.description="PenguinCS Login Server"
            org.opencontainers.image.licenses=MIT

      - name: Build and Push PenguinCS Login
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
          file: PenguinCS.Login/Dockerfile

      # Only do this for release builds
      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v2
      #   with:
      #     subject-name: ghcr.io/ermilburn02/penguincs-login
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true
